# Generated by Django 4.2.9 on 2024-03-09 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='время')),
                ('action', models.CharField(max_length=200, verbose_name='действие')),
                ('sign_of_a_pleasant_habit', models.BooleanField(blank=True, null=True, verbose_name='признак приятной привычки')),
                ('connected_habit', models.CharField(blank=True, max_length=150, null=True, verbose_name='связанная привычка')),
                ('period', models.CharField(max_length=50, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='время на выполнение')),
                ('is_published', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
