# Generated by Django 4.2.9 on 2024-03-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=1, verbose_name='время на выполнение'),
        ),
    ]
